/*
 * Copyright (c) 2026, Carnegie Mellon University.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT
 * HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * dt_queuing.c  dthread queuing (between local threads)
 * 06-May-2026  chuck@ece.cmu.edu
 */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#include "dt_internal.h"

/*
 * block on mgr_notify waiting for a notification if no pending work todo.
 */
void dthread_notifywait(int *morep) {
    int more = 0;
    struct timespec ts;

    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    if (TAILQ_FIRST(&dtrs->dtq.mpirecvq) == NULL &&
        TAILQ_FIRST(&dtrs->dtq.mgrreqq) == NULL) {
        if (dtrs->dtq.notifytimelimit == 0) {
            pthread_cond_wait(&dtrs->dtq.mgr_notify, &dtrs->dtq.dtqlock);
        } else {
            clock_gettime(CLOCK_REALTIME, &ts);
            ts.tv_sec += dtrs->dtq.notifytimelimit;
            pthread_cond_timedwait(&dtrs->dtq.mgr_notify,
                                   &dtrs->dtq.dtqlock, &ts);
        }
    }
    if (TAILQ_FIRST(&dtrs->dtq.mpirecvq) ||
        TAILQ_FIRST(&dtrs->dtq.mgrreqq))   /* more work to do? */
        more++;
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);

    if (morep)
        *morep = more;
}

/*
 * set notify time limit (disabled by default... i.e. dtq.notifytimelimit==0)
 */
void dtq_notifytimelimit(int newval) {
    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    dtrs->dtq.notifytimelimit = (newval < 1) ? 0 : newval;
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);
}

/*
 * allocate a req from the free list (malloc if none free).
 * this is for internal req structured generated by the manager
 * (apps have their own req structures in their ltab[] entry).
 * return req or NULL on memory allocation failure.
 */
dthread_request_t *dtq_req_alloc() {
    dthread_request_t *req;

    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    req = TAILQ_FIRST(&dtrs->dtq.reqfree);
    if (req) {
        TAILQ_REMOVE(&dtrs->dtq.reqfree, req, rl);
    }

    if (!req) {
        if ((req = malloc(sizeof(*req))) != NULL) {
            memset(req, 0, sizeof(*req));
            req->req_ltabidx = -1;   /* internal, not part of ltab[] */
            req->reqstate = DTREQ_INTERNAL;
            dtrs->dtq.nreq++;
            mlog(QUE_DBG, "malloc new req %p, nreq=%d", req, dtrs->dtq.nreq);
        }
    }
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);

    return(req);
}

/*
 * enqueue a req for the manager thread to receive and process.
 */
void dtq_req_enqueue(dthread_request_t *req) {
    int was_empty, ql;
    DT_UNUSED(ql);     /* only used when mlog is enabled */

    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    was_empty = (TAILQ_FIRST(&dtrs->dtq.mpirecvq) == NULL &&
                 TAILQ_FIRST(&dtrs->dtq.mgrreqq) == NULL);
    TAILQ_INSERT_TAIL(&dtrs->dtq.mgrreqq, req, rl);
    dtrs->dtq.mgrrqlen++;
    ql = dtrs->dtq.mgrrqlen;
    if (dtrs->dtq.mgrrqlen > dtrs->dtq.mgrmaxrqlen)
        dtrs->dtq.mgrmaxrqlen = dtrs->dtq.mgrrqlen;

    if (was_empty) {
        pthread_cond_signal(&dtrs->dtq.mgr_notify);
    }

    pthread_mutex_unlock(&dtrs->dtq.dtqlock);

    mlog(QUE_DBG, "req_enqueue req=%p, notify=%d, qlen=%d", req,
         was_empty, ql);
}

/*
 * dequeue and return the first req on the mgrreqq queue, if any.
 * if morep is not null, set to 1 if there is more manager work to do.
 * returns NULL if mgrreqq queue was empty.
 */
dthread_request_t *dtq_req_dequeue(int *morep) {
    dthread_request_t *req;
    int more = 0;

    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    req = TAILQ_FIRST(&dtrs->dtq.mgrreqq);
    if (req) {
        TAILQ_REMOVE(&dtrs->dtq.mgrreqq, req, rl);
        dtrs->dtq.mgrrqlen--;
    }
    if (TAILQ_FIRST(&dtrs->dtq.mpirecvq) ||
        TAILQ_FIRST(&dtrs->dtq.mgrreqq))   /* more work to do? */
        more++;
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);

    if (morep)
        *morep = more;
    if (req)
        mlog(QUE_DBG, "req_dequeue req=%p, more=%d", req, more);
    return(req);
}

/*
 * release a dequeued req that is complete
 */
void dtq_req_release(dthread_request_t *req) {
    mlog(QUE_DBG, "req_release: req=%p", req);

    if (req->reqstate == DTREQ_INTERNAL) {
        /* release internal manager req by adding to free list */
        pthread_mutex_lock(&dtrs->dtq.dtqlock);
        TAILQ_INSERT_HEAD(&dtrs->dtq.reqfree, req, rl);
        pthread_mutex_unlock(&dtrs->dtq.dtqlock);
    } else {
        /* release app thread req by notifying it that req is node */
        pthread_mutex_lock(&req->reqlock);
        req->reqstate = DTREQ_DONE;  /* app thread moves to IDLE when done */
        pthread_cond_signal(&req->reqnotify);
        pthread_mutex_unlock(&req->reqlock);
    }
}

/*
 * allocate a mqe from the free list (malloc if none free).
 * return mqe or NULL on memory allocation failure.
 */
struct dtq_mpiqentry *dtq_mqe_alloc() {
    struct dtq_mpiqentry *mqe;

    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    mqe = TAILQ_FIRST(&dtrs->dtq.mqefree);
    if (mqe) {
        TAILQ_REMOVE(&dtrs->dtq.mqefree, mqe, mql);
    }

    if (!mqe) {
        if ((mqe = malloc(sizeof(*mqe))) != NULL) {
            dtrs->dtq.nmqe++;
            mlog(QUE_DBG, "malloc new mqe %p, nmqe=%d", mqe, dtrs->dtq.nmqe);
        }
    }
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);

    return(mqe);
}

/*
 * undo a mqe allocation that we did not use (due to an error).
 * this is different than the "release" op that happens after
 * we finish with a used mqe that was dequeued mpisendq/mpirecvq.
 */
void dtq_mqe_unalloc(struct dtq_mpiqentry *mqe) {
    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    TAILQ_INSERT_HEAD(&dtrs->dtq.mqefree, mqe, mql);
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);
}

/*
 * enqueue a mqe for the mpi thread to send.  returns NULL on success.
 * if we are draining and cannot send, we return the mqe back to the
 * caller to dispose of.
 *
 * XXX: check if we are our own peer, and q directly on recvq if so!
 */
struct dtq_mpiqentry *dtq_send_enqueue(struct dtq_mpiqentry *mqe) {
    struct dtq_mpiqentry *rv = NULL;

    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    if (dtrs->dtq.mpisq_draindown) {
        rv = mqe;
        mlog(QUE_ERR, "send_enqueue to %d failed: draining", mqe->peer);
    } else {
        /* no need to notify mpi thread since it polls mpisendq */
        TAILQ_INSERT_TAIL(&dtrs->dtq.mpisendq, mqe, mql);
        dtrs->dtq.mpisqlen++;
        if (dtrs->dtq.mpisqlen > dtrs->dtq.mpimaxsqlen)
            dtrs->dtq.mpimaxsqlen = dtrs->dtq.mpisqlen;
        mlog(QUE_DBG, "send_enqueue mqe=%p, peer=%d, len=%d, qlen=%d",
             mqe, mqe->peer, mqe->flen, dtrs->dtq.mpisqlen);
    }
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);

    return(rv);
}

/*
 * dqeueue and return the first mqe on the send queue, if any.
 * returns NULL if sendq was empty.
 */
struct dtq_mpiqentry *dtq_send_dequeue() {
    struct dtq_mpiqentry *mqe;

    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    mqe = TAILQ_FIRST(&dtrs->dtq.mpisendq);
    if (mqe) {
        TAILQ_REMOVE(&dtrs->dtq.mpisendq, mqe, mql);
        dtrs->dtq.mpisqlen--;
        dtrs->dtq.mpindequeuedsends++;
        mlog(QUE_DBG, "send_dequeue mqe=%p", mqe);
    }
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);

    return(mqe);
}

/*
 * release a dequeued mqe used for sending to free list for reuse
 */
void dtq_send_release(struct dtq_mpiqentry *mqe) {
    int just_drained;

    mlog(QUE_DBG, "send_release mqe=%p", mqe);
    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    dtrs->dtq.mpindequeuedsends--;
    TAILQ_INSERT_HEAD(&dtrs->dtq.mqefree, mqe, mql);
    just_drained = (dtrs->dtq.mpisq_draindown != 0 && dtrs->dtq.mpisqlen == 0
                    && dtrs->dtq.mpindequeuedsends == 0);
    if (just_drained) {
        dtrs->dtq.mpisq_draindown = DTQ_DD_DRAINED;
        pthread_cond_signal(&dtrs->dtq.mgr_notify);
    }
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);

    if (just_drained)
        mlog(QUE_DBG, "send_release: just drained!");
}

/*
 * enqueue a mqe for the manager thread to receive and process.
 */
void dtq_recv_enqueue(struct dtq_mpiqentry *mqe) {
    int was_empty, ql;
    DT_UNUSED(ql);     /* only used when mlog is enabled */

    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    was_empty = (TAILQ_FIRST(&dtrs->dtq.mpirecvq) == NULL &&
                 TAILQ_FIRST(&dtrs->dtq.mgrreqq) == NULL);
    TAILQ_INSERT_TAIL(&dtrs->dtq.mpirecvq, mqe, mql);
    dtrs->dtq.mpirqlen++;
    ql = dtrs->dtq.mpirqlen;
    if (dtrs->dtq.mpirqlen > dtrs->dtq.mpimaxrqlen)
        dtrs->dtq.mpimaxrqlen = dtrs->dtq.mpirqlen;

    if (was_empty) {
        pthread_cond_signal(&dtrs->dtq.mgr_notify);
    }
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);

    mlog(QUE_DBG, "recv_enqueue mqe=%p, notify=%d, qlen=%d", mqe,
         was_empty, ql);
}

/*
 * dqeueue and return the first mqe on the recv queue, if any.
 * if morep is not null, set to 1 if there is more manager work to do.
 * returns NULL if recv queue was empty.
 */
struct dtq_mpiqentry *dtq_recv_dequeue(int *morep) {
    struct dtq_mpiqentry *mqe;
    int more = 0;

    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    mqe = TAILQ_FIRST(&dtrs->dtq.mpirecvq);
    if (mqe) {
        TAILQ_REMOVE(&dtrs->dtq.mpirecvq, mqe, mql);
        dtrs->dtq.mpirqlen--;
    }
    if (TAILQ_FIRST(&dtrs->dtq.mpirecvq) ||
        TAILQ_FIRST(&dtrs->dtq.mgrreqq))   /* more work to do? */
        more++;
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);

    if (morep)
        *morep = more;
    if (mqe)
        mlog(QUE_DBG, "recv_dequeue mqe=%p, more=%d", mqe, more);
    return(mqe);
}

/*
 * release a dequeued mqe used for recv to free list for reuse
 */
void dtq_recv_release(struct dtq_mpiqentry *mqe) {
    mlog(QUE_DBG, "recv_release: mqe=%p", mqe);
    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    TAILQ_INSERT_HEAD(&dtrs->dtq.mqefree, mqe, mql);
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);
}

/*
 * start mpisendq draindown operation so we can shutdown.  this
 * sets mpisq_draindown which blocks any additional mqes from
 * being added to mpisendq.   we return the number of outstanding
 * mqes (either in mpisendq or being processed by MPI).   if
 * we return 0, then caller can do the next step of the shutdown now.
 * otherwise, the caller should wait for a DTQ_DD_DRAINED state
 * before moving forward.
 */
int dtq_send_draindown() {
    int old, rv;
    DT_UNUSED(old);    /* only used when mlog is enabled */

    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    old = dtrs->dtq.mpisq_draindown;
    rv = dtrs->dtq.mpisqlen + dtrs->dtq.mpindequeuedsends;
    dtrs->dtq.mpisq_draindown = (rv) ? DTQ_DD_DRAINING : DTQ_DD_DRAINED;
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);

    mlog(QUE_DBG, "send_draindown (old=%d, rv=%d)", old, rv);
    return(rv);
}

/*
 * return current drain state
 */
int dtq_send_drainstate() {
    int rv;

    pthread_mutex_lock(&dtrs->dtq.dtqlock);
    rv = dtrs->dtq.mpisq_draindown;
    pthread_mutex_unlock(&dtrs->dtq.dtqlock);

    return(rv);
}

/*
 * dtq_stats.  load stats into provided dtq_stats structure.
 */
void dtq_stats(struct dtq_stats *qs) {
    qs->nmqe = dtrs->dtq.nmqe;
    qs->nreq = dtrs->dtq.nreq;
    qs->mpimaxsqlen = dtrs->dtq.mpimaxsqlen;
    qs->mpimaxrqlen = dtrs->dtq.mpimaxrqlen;
    qs->mgrmaxrqlen = dtrs->dtq.mgrmaxrqlen;
}

/*
 * dtq_init.   setup local thread queuing data structures before putting
 * them in service.  return 0 on success, -1 on error.
 */
int dtq_init() {
    memset(&dtrs->dtq, 0, sizeof(*&dtrs->dtq));    /* init all to zero */
    pthread_mutex_init(&dtrs->dtq.dtqlock, NULL);

    TAILQ_INIT(&dtrs->dtq.mgrreqq);
    pthread_cond_init(&dtrs->dtq.mgr_notify, NULL);
    TAILQ_INIT(&dtrs->dtq.reqfree);
    TAILQ_INIT(&dtrs->dtq.mpisendq);
    TAILQ_INIT(&dtrs->dtq.mpirecvq);
    TAILQ_INIT(&dtrs->dtq.mqefree);

    mlog(QUE_DBG, "mpiq_init: complete");
    return(0);
}

/*
 * dtq_finalize.  should be called by manager thread during shutdown.
 * make sure all processing has stopped before trying to finalize the
 * queues (i.e. locking no longer needed).
 */
void dtq_finalize() {
    dthread_request_t *req;
    struct dtq_mpiqentry *mqe;

    /* clear orphaned internal reqs.  app reqs will be freed with ltab[] */
    while ((req = TAILQ_FIRST(&dtrs->dtq.mgrreqq)) != NULL) {
        TAILQ_REMOVE(&dtrs->dtq.mgrreqq, req, rl);
        if (req->reqstate == DTREQ_INTERNAL) {
            free(req);
        }
    }

    /* clear req free list */
    while ((req = TAILQ_FIRST(&dtrs->dtq.reqfree)) != NULL) {
        TAILQ_REMOVE(&dtrs->dtq.reqfree, req, rl);
        free(req);
    }

    /* drop/free send mqes waiting for isend */
    while ((mqe = TAILQ_FIRST(&dtrs->dtq.mpisendq)) != NULL) {
        mlog(QUE_DBG, "finalize drop send mqe %p", mqe);
        TAILQ_REMOVE(&dtrs->dtq.mpisendq, mqe, mql);
        free(mqe);
    }

    /* drop/free recv mqes waiting for mgr */
    while ((mqe = TAILQ_FIRST(&dtrs->dtq.mpirecvq)) != NULL) {
        mlog(QUE_DBG, "finalize drop recv mqe %p", mqe);
        TAILQ_REMOVE(&dtrs->dtq.mpirecvq, mqe, mql);
        free(mqe);
    }

    /* and clear the free list */
    while ((mqe = TAILQ_FIRST(&dtrs->dtq.mqefree)) != NULL) {
        TAILQ_REMOVE(&dtrs->dtq.mqefree, mqe, mql);
        free(mqe);
    }

    mlog(QUE_INFO, "dtq_finalize complete with nreq=%d nmqe=%d",
         dtrs->dtq.nreq, dtrs->dtq.nmqe);
}
